# Don't touch me unless you know exactly what you are doing
# All of this can be edited in game using commands

event-world: event
spawn-loc:
  world: world
  x: 0
  y: 70
  z: 0
  yaw: 0
  pitch: 0

events:
  brackets:
    enabled: false
    spec-location:
      x: 0
      y: 70
      z: 0
      yaw: 0
      pitch: 0
    start-location-1:
      x: 0
      y: 70
      z: 0
      yaw: 0
      pitch: 0
    start-location-2:
      x: 0
      y: 70
      z: 0
      yaw: 0
      pitch: 0

  woolshuffle:
    enabled: false
    spec-location:
      x: 0
      y: 70
      z: 0
      yaw: 0
      pitch: 0
    start-location:
      x: 0
      y: 70
      z: 0
      yaw: 0
      pitch: 0

  spleef:
    enabled: false
    snow-position-1:
      x: 0
      y: 70
      z: 0
    snow-position-2:
      x: 0
      y: 70
      z: 0
    spec-location:
      x: 0
      y: 70
      z: 0
      yaw: 0
      pitch: 0
    start-location-1:
      x: 0
      y: 70
      z: 0
      yaw: 0
      pitch: 0
    start-location-2:
      x: 0
      y: 70
      z: 0
      yaw: 0
      pitch: 0
    region: spleef
      